version: 2.1

orbs:
  whitesource-scan: whitesource/whitesource-scan@18.10.2

workflows:
  test:
    jobs:
    - whitesource-scan/scan:
    context: WhiteSource
    api_key: $API_KEY
    config_file_path: "https://s3.amazonaws.com/file-system-agent/SNAPSHOT/whitesource-fs-agent.config"
