# Java Maven CircleCI 2.1 configuration file
#

version: 2.1

orbs:
  vulnerability-checker: philipbox/vulnachecka@0.0.3

jobs:
  build:
    executor:
    - whitesource-scan/scan:
        name: java
        image-name: chen470/fsa
        image-tag: "18.11.1"
    steps:
      - checkout

workflows:
  build:
    jobs:
    - vulnerability-checker/scan
