version: 2.1

orbs:
  scan: whitesource/whitesource-scan@18.10.2

workflows:
  test:
    jobs:
    - scan/whitesource-scan:
    context: WhiteSource
    api_key: *
    config_file_path: "https://s3.amazonaws.com/file-system-agent/SNAPSHOT/whitesource-fs-agent.config"
