# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: 2.1
description: "The orb integrates Vulnerability Checker, a tool which checks your code against the top 50 open source vulnerabilities and gives a result in HTML file in artifacts"

executors:
  java:
    description: The docker container to run java commands
    docker:
      - image: circleci/openjdk:8-jdk

jobs:
  scan:
    executor: java
    parameters:
      directory:
        description: directory to scan.
        type: string
        default: "."
    steps:
      - checkout
      - run:
          command: |
              chown -R $USER:$USER .
              mkdir -p /results
              cp *.html /results
      - store_artifacts:
          path: /results
workflows:
  build:
    jobs:
    - scan
  version: 2.1
